language: go

go:
  - 1.14.x

os:
  - linux

services:
  - docker

env:
  - GO111MODULE=on

before_install:
  - GO111MODULE=on
  - docker build -f ./blog_frontend/Dockerfile.prod -t zoomiraja/blogfrontend ./blog_frontend/
  - docker build -f ./blog_api/Dockerfile.prod -t zoomiraja/goblog ./blog_api/

script:
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
  - docker push zoomiraja/blogfrontend
  - docker push zoomiraja/goblog

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: web-blog
  env: WebBlog-env-2
  bucket_name: elasticbeanstalk-us-east-2-960149412742
  bucket_path: web-blog
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
