version: "2"
services:
  blog_api:
    image: blog_api
    container_name: blog_api
    build: ./blog_api
    ports:
      - 80:8000
    volumes:
      - ./blog_api/:/app
    environment:
      - API_PORT=8000
  db:
    image: mysql:5.6
    container_name: go_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: goDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
  persistent: