version: "2"
services:
  blog_api:
    image: blog_api
    container_name: blog_api
    build: ./blog_api
    depends_on:
      - db
    ports:
      - 80:8000
    volumes:
      - ./blog_api/:/app
    environment:
      - API_PORT=8000
  blog_frontend:
    image: blog_frontend
    container_name: blog_frontend
    build: ./blog_frontend
    volumes:
      - ./blog_frontend:/app
      - blog_front_modules:/app/node_modules
      - blog_build:/app/.next
    ports:
      - 3001:3000
  db:
    image: mysql:5.6
    container_name: go_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: goDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
volumes:
  persistent:
  blog_front_modules:
  blog_build: